django_postgres_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('inf553/', include('inf553.urls')),
    path('admin/', admin.site.urls),
]

inf553/urls.py
from django.urls import path

from . import views

app_name = 'inf553'
urlpatterns = [
    path('', views.index, name='index'),
    path('<table>/', views.detail, name = 'detail'),
]

inf553/models.py
from django.db import models

# Create your models here.

inf553/views.py
from django.http.response import HttpResponse
from django.template import loader
from django.shortcuts import render
import psycopg2

def index(request):
    #database connection variables
    host = "localhost"
    database="movie_test"
    user="postgres"
    password="176211"
    port=5432
    #connect to postgres and query the FK-PK pairs of tables
    con = psycopg2.connect(host=host,database=database,  user=user, password=password, port=port)
    query = """SELECT tablename
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND
    schemaname != 'information_schema'; """
    #print(query)

    cur = con.cursor()
     # create view myattr
    query_7 = "create view myattr as with mytables as (select c.oid, c.relname from pg_class c, pg_namespace n where c.relkind='r' and n.oid=c.relnamespace and not(nspname like 'pg_%' or nspname='information_schema')) select t.relname, a.attname, y.typname from mytables t, pg_attribute a, pg_type y where t.oid=a.attrelid and a.atttypid=y.oid and y.typname='varchar';"
    cur.execute(query_7)
    con.commit()

    cur.execute(query)
    tables = cur.fetchall()

    # # create view myattr
    # query_7 = "create view myattr as with mytables as (select c.oid, c.relname from pg_class c, pg_namespace n where c.relkind='r' and n.oid=c.relnamespace and not(nspname like 'pg_%' or nspname='information_schema')) select t.relname, a.attname, y.typname from mytables t, pg_attribute a, pg_type y where t.oid=a.attrelid and a.atttypid=y.oid and y.typname='varchar';"
    # cur.execute(query_7)
    template = loader.get_template('inf553/index.html')
    context = {
        'tables': tables,
    }
    #return render(request, 'inf553/index.html', {'tables': tables})
    return HttpResponse(template.render(context, request))


def detail(request, table):
    #database connection variables
    host = "localhost"
    database="movie_test"
    user="postgres"
    password="176211"
    port=5432
    #connect to postgres and query the FK-PK pairs of tables
    con = psycopg2.connect(host=host,database=database,  user=user, password=password, port=port)
    
    # Queries set

    query_4 = "SELECT c.relname, a.amname FROM pg_class c, pg_namespace n, pg_am a WHERE (c.relkind = 'r' or c.relkind = 'i') AND n.oid = c.relnamespace AND not(nspname like 'pg_%' or nspname = 'information_schema') and c.relam = a.oid "
    full_query_4 = query_4 + "and c.relname = '%s'; "%table
    
    query_5 = "with mytables as (select c.oid, c.relname FROM pg_class c, pg_namespace n WHERE c.relkind='r' and n.oid = c.relnamespace and not (nspname like 'pg_%' or nspname = 'information_schema')) SELECT t.relname, a.attname, y.typname from mytables t, pg_attribute a, pg_type y where t.oid = a.attrelid and a.atttypid = y.oid and y.typname='varchar'"
    full_query_5 = query_5 + "and t.relname = '%s';"%table

    # query_7 = "create view myattr as with mytables as (select c.oid, c.relname from pg_class c, pg_namespace n where c.relkind='r' and n.oid=c.relnamespace and not(nspname like 'pg_%' or nspname='information_schema')) select t.relname, a.attname, y.typname from mytables t, pg_attribute a, pg_type y where t.oid=a.attrelid and a.atttypid=y.oid and y.typname='varchar';"
    full_query_7 = """
with aux as
(select tablename, attname, n_distinct as ndist, histogram_bounds::text::varchar[] as bound
from pg_stats
where (tablename, attname) in (select relname, attname from myattr))
select tablename, attname, ceil(ndist*(-1)*n_live_tup) as distval, bound[1] as min, bound[array_length(bound,
1)] as max   
from aux, pg_stat_user_tables sut
where sut.relname=aux.tablename""" + " and aux.tablename = '%s';"%table

    cur = con.cursor()

    cur.execute(full_query_4)
    results_4 = cur.fetchall()

    cur.execute(full_query_5)
    results_5 = cur.fetchall()
    
    cur.execute(full_query_7)
    results_7 = cur.fetchall()

    results = cur.fetchall()
    template = loader.get_template('inf553/detail.html')
    context = {
        'results_4': results_4, 
        'results_5': results_5,
        'results_7': results_7,
    }
    return HttpResponse(template.render(context, request))

inf553/templates/inf553/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Query result</title>
  </head>
  <body>
  	<h1>The query results of the current table are: </h1>
    <h2>Query_4</h2>
    <font size = "+1.5">For each user table, or index over a user table, return: its internal identifier, its name, and the name of the access method it supports.</font>
    <ul>
    <font size = "+1">
    {% for result in results_4 %}
        <li>{{ result }}</li>
    {% endfor %}
    </font>
    </ul>
    <h2>Query_5</h2>
    <font size = "+1.5">For each table in the current database, not automatically created by Postgres, and each attribute of the table that is of type varchar, return the name of the table, the name of the attribute, and the name of the attribute type.</font>
    <ul>
    <font size = "+1">
    {% for result in results_5 %}
        <li>{{ result }}</li>
    {% endfor %}
    </font>
    </ul>
    <h2>Query_7</h2>
    <font size = "+1.5">Call myattr the table obtained by adding LIMIT 5 to the query from point 5. For every attribute listed in myattr, use pg stats to return: tablename, attname, distval, min and max</font>
    <ul>
    <font size = "+1">
    {% for result in results_7 %}
        <li>{{ result }}</li>
    {% endfor %}
    </font>
    </ul>
  </body>
</html>

inf553/templates/inf553/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>INF553 Projet</title>
    <style>
      .demo{
        width:700px;
        
        background-image: url(" https://www.usinenouvelle.com/mediatheque/0/4/8/000736840_896x598_c.jpg") ;
      } 
      .demo1{
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.7);
      }
      
    </style>
                              
  </head>

  <body >
    <div align = "center">
      
      <div>
        <h1>INF553 DBMS Project</h1>

        <font size = "+2" ><em>Zhengqing Liu</em></font> <br><br>
        <font size = "+1.5" >December 2021</font> <br><br> <br><br>
        <font size = "+1.5">This project is aimed to build a web application to return some results of queries. It is mainly developed by Django and Postgresql.</font> <br><br><br><br>
        <img src = "https://www.usinenouvelle.com/mediatheque/0/4/8/000736840_896x598_c.jpg">
        <h2>The tables of the current database are: </h2>
        <font size = "+1.5">click below to see the query results</font><br>
        <font size = "+1">
        <ul>
        {% for table in tables %}
            <a href = "{% url 'inf553:detail' table.0 %}">{{ table.0 }}</a><br>
        {% endfor %}
        </ul>
        <ul>
        </font>
      </div>
      <img src = "https://programmes.polytechnique.edu/themes/custom/x_theme_bulma/images/polytechnique.jpg"  width = '400'>
    </div>
  </body>
</html>